import os
import glob
import numpy as np
import soundfile as sf
import torch
from transformers import Wav2Vec2FeatureExtractor, Wav2Vec2ForSequenceClassification
from datetime import datetime

# ==========================================
# CONFIG
# ==========================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_DIR = os.path.join(BASE_DIR, "audio_input")
OUTPUT_DIR = os.path.join(BASE_DIR, "audio_output")

# MODEL: Speech Emotion Recognition (SER)
# "superb/wav2vec2-base-superb-er"
# We define Depression as high "Sad" score + high "Neutral" score.
MODEL_NAME = "superb/wav2vec2-base-superb-er"

def analyze_depression(audio_file):
    try:
        # Load
        feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(MODEL_NAME)
        model = Wav2Vec2ForSequenceClassification.from_pretrained(MODEL_NAME)
        
        # Read
        import librosa
        speech, sr = librosa.load(audio_file, sr=16000)
        
        # Process
        inputs = feature_extractor(speech, sampling_rate=16000, return_tensors="pt", padding=True)
        
        with torch.no_grad():
            logits = model(**inputs).logits
            
        probs = torch.nn.functional.softmax(logits, dim=-1)
        scores = probs[0].tolist()
        
        # Superb ER labels: 0:neu, 1:hap, 2:ang, 3:sad
        neutral = scores[0]
        happy = scores[1]
        angry = scores[2]
        sad = scores[3]
        
        # LOGIC:
        # Depression Score = Sadness + (Neutral * 0.5) - Happiness
        # If you sound sad and flat, High Risk. If you sound happy, Low Risk.
        dep_score = sad + (neutral * 0.5) - (happy * 0.5)
        
        # Normalize roughly to 0-1
        dep_score = max(0.0, min(1.0, dep_score))
        
        return "Potential Depression" if dep_score > 0.4 else "Healthy", dep_score

    except Exception as e:
        print(f"Error analyzing {audio_file}: {e}")
        return "Error", 0.0

def generate_report(filename, prediction, probability, all_results=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    res_table = "| Run # | Result | Depression Score |\n| :--- | :--- | :--- |\n"
    if all_results:
        for idx, (lbl, prob) in enumerate(all_results):
            res_table += f"| {idx+1} | {lbl} | {prob:.2%} |\n"
    else:
        res_table += f"| 1 | {prediction} | {probability:.2%} |\n"

    report_content = f"""# Depression Mental Health Screening Report
    
**Date:** {timestamp}
**File:** {filename}
**Model:** {MODEL_NAME} (Real Sentiment Analysis)

## Methodology
Using Speech Emotion Recognition (SER) to detect "Flat Affect" and "Sadness".
- **Sadness:** High volume of sad phonetic markers.
- **Neutrality:** Lack of emotional variance (Monotone).

## Consistency Check (5 Runs)
{res_table}

## Final Results
- **Status:** {prediction}
- **Depression Score:** {probability:.2%}

---
*Generated by Synapxe Health screening prototype*
"""
    
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    output_filename = os.path.splitext(filename)[0] + "_depression_report.md"
    output_path = os.path.join(OUTPUT_DIR, output_filename)
    
    with open(output_path, "w") as f:
        f.write(report_content)
    print(f"Report generated: {output_path}")

def main():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
    
    files = glob.glob(os.path.join(INPUT_DIR, "*.wav"))
    if not files: return

    for f in files:
        print(f"\nProcessing {os.path.basename(f)} (5 Runs)...")
        results = []
        for _ in range(5):
            res, prob = analyze_depression(f)
            results.append((res, prob))
            print(f"  Run: {res} ({prob:.2%})")
            
        final_res, final_prob = results[-1]
        generate_report(os.path.basename(f), final_res, final_prob, results)

if __name__ == "__main__":
    main()
