import os
import glob
import numpy as np
import librosa
from datetime import datetime

# ==========================================
# CONFIG
# ==========================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_DIR = os.path.join(BASE_DIR, "audio_input")
OUTPUT_DIR = os.path.join(BASE_DIR, "audio_output")

# MODEL: Algorithmic Speech Analysis (No Neural Net needed for pauses)
# Cognitive decline involves: Slow speech, many pauses, simple words.

def analyze_cognitive(audio_file):
    try:
        # Load audio
        y, sr = librosa.load(audio_file)
        
        # 1. Detect Silence / Pauses
        # split returns non-silent intervals
        non_silent_intervals = librosa.effects.split(y, top_db=20) 
        
        total_duration = librosa.get_duration(y=y, sr=sr)
        non_silent_duration = sum([end - start for start, end in non_silent_intervals]) / sr
        
        pause_duration = total_duration - non_silent_duration
        pause_ratio = pause_duration / total_duration
        
        # 2. Speech Rate (Approx syllables per second)
        # We count peaks in the spectral flux as 'syllable-like' events
        onset_env = librosa.onset.onset_strength(y=y, sr=sr)
        # Using a very simple method: count peaks in envelope
        peaks = librosa.util.peak_pick(onset_env, pre_max=3, post_max=3, pre_avg=3, post_avg=3, delta=0.5, wait=10)
        num_syllables = len(peaks)
        
        # Calculate BPM / Syllables per second
        # If the file is very short, tempo estimation is garbage, so use raw count
        syllables_per_sec = num_syllables / total_duration if total_duration > 0 else 0
        
        # LOGIC:
        # High Pause Ratio (> 40%) OR Very Slow Tempo (< 2 syllables/sec) -> Cognitive Risk
        
        risk_score = 0.0
        # If > 30% is silence, add risk
        risk_score += min(1.0, (pause_ratio / 0.5)) * 0.5 
        
        # If < 3 syllables/sec, add risk
        if syllables_per_sec < 3.0:
            risk_score += 0.5
            
        return "Signs Detected" if risk_score > 0.6 else "Normal", risk_score

    except Exception as e:
        print(f"Error analyzing {audio_file}: {e}")
        return "Error", 0.0

def generate_report(filename, prediction, probability, all_results=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    res_table = "| Run # | Result | Cognitive Risk Score |\n| :--- | :--- | :--- |\n"
    if all_results:
        for idx, (lbl, prob) in enumerate(all_results):
            res_table += f"| {idx+1} | {lbl} | {prob:.2%} |\n"
    else:
        res_table += f"| 1 | {prediction} | {probability:.2%} |\n"

    report_content = f"""# Cognitive Health Screening Report
    
**Date:** {timestamp}
**File:** {filename}
**Model:** Acoustic Algorithmic Analysis (Librosa)

## Methodology
- **Pause Ratio:** Measuring silence vs speech.
- **Tempo:** Measuring speech speed (BPM).
*Slow speech + frequent pauses are strong indicators of MCI.*

## Consistency Check (5 Runs)
{res_table}

## Final Results
- **Status:** {prediction}
- **Risk Score:** {probability:.2%}

---
*Generated by Synapxe Health screening prototype*
"""
    
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    output_filename = os.path.splitext(filename)[0] + "_cognitive_report.md"
    output_path = os.path.join(OUTPUT_DIR, output_filename)
    
    with open(output_path, "w") as f:
        f.write(report_content)
    print(f"Report generated: {output_path}")

def main():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
    
    files = glob.glob(os.path.join(INPUT_DIR, "*.wav"))
    if not files: return

    for f in files:
        print(f"\nProcessing {os.path.basename(f)} (5 Runs)...")
        results = []
        for _ in range(5):
            res, prob = analyze_cognitive(f)
            results.append((res, prob))
            print(f"  Run: {res} ({prob:.2%})")
            
        final_res, final_prob = results[-1]
        generate_report(os.path.basename(f), final_res, final_prob, results)

if __name__ == "__main__":
    main()
