import os
import glob
from datetime import datetime
import sys

# Add paths to sys for imports
sys.path.append(os.path.join(os.path.dirname(__file__), "VoiceFatigue"))
sys.path.append(os.path.join(os.path.dirname(__file__), "CognitiveDecline"))
sys.path.append(os.path.join(os.path.dirname(__file__), "DepressionScreening"))

# Import functions from our NEW files
from detect_voice_fatigue import analyze_fatigue
from detect_cognitive_decline import analyze_cognitive
from detect_depression import analyze_depression

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
INPUT_DIR = os.path.join(BASE_DIR, "audio_input")
OUTPUT_DIR = os.path.join(BASE_DIR, "audio_output")
REPORT_FILE = os.path.join(OUTPUT_DIR, "Combined_Health_Report.md")

def main():
    if not os.path.exists(INPUT_DIR):
        print("No input directory found.")
        return
        
    files = glob.glob(os.path.join(INPUT_DIR, "*.wav"))
    if not files:
        print("No .wav files found in audio_input")
        return
    
    # Prepare Report Header
    report_lines = []
    report_lines.append(f"# Consolidated Health Screening Report")
    report_lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    report_lines.append(f"**Files Analyzed:** {len(files)}")
    report_lines.append(f"**System System:** Real-Time Inference (Pre-trained Models)")
    report_lines.append(f"\nAll models are now using Real-World Pre-trained weights (HuggingFace) or Algorithmic Physics (Librosa). NO RANDOM GUESSING.")
    report_lines.append(f"\n---")

    for f in files:
        filename = os.path.basename(f)
        print(f"\nAnalyzing {filename} (Running 5 iterations per model)...")
        
        report_lines.append(f"\n## File: {filename}")
        report_lines.append(f"| Screening Type | Run #1 | Run #2 | Run #3 | Run #4 | Run #5 |")
        report_lines.append(f"| :--- | :--- | :--- | :--- | :--- | :--- |")

        # Store results for each run
        fatigue_results = []
        cognitive_results = []
        depression_results = []

        # Run 5 times (should be consistent now naturally)
        for _ in range(5):
            # 1. Fatigue (HuBERT Emotion)
            f_res, f_conf = analyze_fatigue(f)
            fatigue_results.append(f"{f_res}<br>({f_conf:.2%})")
            
            # 2. Cognitive (Librosa Physics)
            c_res, c_conf = analyze_cognitive(f)
            cognitive_results.append(f"{c_res}<br>({c_conf:.2%})")
            
            # 3. Depression (Wav2Vec Emotion)
            d_res, d_conf = analyze_depression(f)
            depression_results.append(f"{d_res}<br>({d_conf:.2%})")

        # Add single row per type
        report_lines.append(f"| **Voice Fatigue** | {fatigue_results[0]} | {fatigue_results[1]} | {fatigue_results[2]} | {fatigue_results[3]} | {fatigue_results[4]} |")
        report_lines.append(f"| **Cognitive Decline** | {cognitive_results[0]} | {cognitive_results[1]} | {cognitive_results[2]} | {cognitive_results[3]} | {cognitive_results[4]} |")
        report_lines.append(f"| **Depression** | {depression_results[0]} | {depression_results[1]} | {depression_results[2]} | {depression_results[3]} | {depression_results[4]} |")
        
        report_lines.append(f"\n")

    report_lines.append("---\n*Generated by Synapxe Real-Model Prototype*\n")

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    with open(REPORT_FILE, "w") as f:
        f.write("\n".join(report_lines))
        
    print(f"\nSuccess! Combined report saved to: {REPORT_FILE}")

if __name__ == "__main__":
    main()
