import os
import glob
import numpy as np
import soundfile as sf
import torch
from transformers import Wav2Vec2FeatureExtractor, HubertForSequenceClassification
from datetime import datetime

# ==========================================
# CONFIGURATION
# ==========================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_DIR = os.path.join(BASE_DIR, "audio_input")
OUTPUT_DIR = os.path.join(BASE_DIR, "audio_output")

# MODEL (Using Emotion Recognition as a proxy for Fatigue/Arousal)
# "superb/hubert-base-superb-er" is excellent for emotion/state detection
MODEL_NAME = "superb/hubert-base-superb-er"

def analyze_fatigue(audio_file):
    try:
        # Load Model & Feature Extractor (Not Processor, as we don't need text decoding)
        feature_extractor = Wav2Vec2FeatureExtractor.from_pretrained(MODEL_NAME)
        model = HubertForSequenceClassification.from_pretrained(MODEL_NAME)
        
        # Load Audio (Resample to 16kHz)
        speech, rate = sf.read(audio_file)
        if rate != 16000:
            # Simple resampling (nearest neighbor usually fine for demos, but librosa better)
            import librosa
            speech, _ = librosa.load(audio_file, sr=16000)
            
        # Preprocess
        inputs = feature_extractor(speech, sampling_rate=16000, return_tensors="pt", padding=True)
        
        # Inference
        with torch.no_grad():
            logits = model(**inputs).logits
            
        # Get Probabilities
        probs = torch.nn.functional.softmax(logits, dim=-1)
        scores = probs[0].tolist()
        
        # Labels for this specific model (neu, hap, ang, sad)
        # We interpret:
        # - Sad / Neutral -> Low Energy (Fatigue Risk)
        # - Happy / Angry -> High Energy
        
        # Index map: 0: neu, 1: hap, 2: ang, 3: sad
        # (This varies by model version, we assume standard Superb mapping)
        # Actually Superb ER usually maps: 0: neu, 1: hap, 2: ang, 3: sad.
        
        fatigue_score = scores[0] + scores[3] # Neutral + Sad
        energy_score = scores[1] + scores[2]  # Happy + Angry
        
        return "High Fatigue Risk" if fatigue_score > energy_score else "Normal Energy", fatigue_score

    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"Error analyzing {audio_file}: {e}")
        return "Error", 0.0

def generate_report(filename, prediction, probability, all_results=None):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Build results table
    res_table = "| Run # | Result | Fatigue Score |\n| :--- | :--- | :--- |\n"
    if all_results:
        for idx, (lbl, prob) in enumerate(all_results):
            res_table += f"| {idx+1} | {lbl} | {prob:.2%} |\n"
    else:
        res_table += f"| 1 | {prediction} | {probability:.2%} |\n"

    report_content = f"""# Voice Fatigue Analysis Report
    
**Date:** {timestamp}
**File:** {filename}
**Model:** {MODEL_NAME} (Real Pre-Trained Model)

## Consistency Check (5 Runs)
*Note: Using a real model, this should be consistent natively.*
{res_table}

## Final Analysis
- **Status:** {prediction}
- **Fatigue/Arousal Score:** {probability:.2%}
(High Score = Low energy/monotone voice detected)

---
*Generated by Synapxe Health screening prototype*
"""
    
    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    output_filename = os.path.splitext(filename)[0] + "_fatigue_report.md"
    output_path = os.path.join(OUTPUT_DIR, output_filename)
    
    with open(output_path, "w") as f:
        f.write(report_content)
    print(f"Report generated: {output_path}")

def main():
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR)
    
    files = glob.glob(os.path.join(INPUT_DIR, "*.wav"))
    if not files:
        print("No files found.")
        return

    for f in files:
        print(f"\nProcessing {os.path.basename(f)} (5 Runs)...")
        results = []
        for _ in range(5):
            res, prob = analyze_fatigue(f)
            results.append((res, prob))
            print(f"  Run: {res} ({prob:.2%})")
            
        final_res, final_prob = results[-1]
        generate_report(os.path.basename(f), final_res, final_prob, results)

if __name__ == "__main__":
    main()
